apiVersion: v1
kind: Service
metadata:
  name: spring-hello-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: spring-hello
  ports:
    - port: 80
      targetPort: 8080